/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package A1B2;

import A1B2.Demo1A2B;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;
import java.util.Date;

/**
 *
 * @author 小官
 */
public class WebGame extends javax.swing.JFrame {
String Ans = Demo1A2B.creatAnswer();
    

    public void getGuess() {
        //拿到數字
        String Guess = jTextField1.getText();
///檢查長度
        boolean checkLength = Demo1A2B.checkLength(Guess);
        if (checkLength == false) {
            JOptionPane.showConfirmDialog(null, "請輸入四位數字");
        } else {
            boolean checkAllisNum = Demo1A2B.checkAllisNum(Guess);
            if (checkAllisNum == false) {
                JOptionPane.showMessageDialog(null, "只能輸入數字");
            } else {
                boolean checkSameNum = Demo1A2B.checkSameNum(Guess);
                if (checkSameNum == false) {
                    JOptionPane.showMessageDialog(null, "數字不能重複");
                } else {
                    Demo1A2B.getCount();
                    jLabel2.setText("猜題次數:" + Demo1A2B.getCount());
                }
            }
        }
    }

    public void newAnswer() {
        String Ans = Demo1A2B.creatAnswer();
        jTextPane1.setText("猜題紀錄");
        jTextField3.setText(Ans);
//not work
    }
    String A= new String();//讓下面可以再接一個變數

    public void CompareAns() {
                
        String CompareAns = Demo1A2B.show1A2B(Ans, jTextField1.getText());
              A = A + ("第" + Demo1A2B.getCount() + "次猜數:\t" + jTextField1.getText() + "\n結果:\t" + CompareAns + "\n");

        jTextPane1.setText(A);
            Demo1A2B.count++;//這裡加COUNT
        if (Demo1A2B.show1A2B(Ans, jTextField1.getText()).equals("4A0B")) {
            JOptionPane.showMessageDialog(null, "恭喜答對!");
        }
    }

    public void StartTime() {
//    int seconds = time.getSeconds();
//long StartTime=System.currentTimeMillis();
//System.out.println(LocalDateTime.now().getSecond()); 
        Date d = new Date();
        System.out.println("Second of the minute is  : " + d.getSeconds());
    }

    /**
     * Creates new form WebGame
     */
    public WebGame() {
        initComponents();
        Setcion();
      
    }

    /**
     *
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("猜數字遊戲 1A2B");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setPreferredSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        jLabel1.setText("請輸入數字:");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 320, 73, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(108, 324, 97, 30);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("遊戲說明:\n電腦會想好一組四個數碼\n（數碼0可以在最前面，且數碼不可以重複出現被使用），\n例如0847，讓猜題者去猜。\nEX: 猜題者輸入6049，則提示是1A1B，\nA表示有此數，且在正確位置， B表示有此數字，但位置不對。\n用這樣的遊戲規則，猜電腦中設的數字。");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(31, 10, 444, 139);

        jButton2.setText("我猜");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 330, 57, 23);

        jTextPane1.setEditable(false);
        jTextPane1.setText("猜題紀錄");
        jScrollPane2.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(31, 149, 248, 168);

        jLabel2.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        jLabel2.setText("猜題次數:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(316, 167, 90, 20);

        jLabel3.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        jLabel3.setText("猜題秒數:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(316, 193, 110, 20);

        jButton3.setText("正確答案");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(316, 260, 81, 23);

        jTextField3.setEditable(false);
        jTextField3.setText("****");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(316, 293, 81, 30);

        jButton1.setText("重新開始");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(316, 227, 81, 23);

        getAccessibleContext().setAccessibleDescription("");

        setSize(new java.awt.Dimension(516, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        getGuess();
        CompareAns();


//jLabel3.setVerticalTextPosition(StarTime());// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        jTextField3.setText(Ans);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MousePressed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed

//jTextField3.setText(Demo1A2B.creatAnswer());// TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
newAnswer();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WebGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WebGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WebGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WebGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WebGame().setVisible(true);

            }
            //JFrame frame = new JFrame("猜數字遊戲");

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    private void Setcion() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
